### ISSUE TITLE
Unable to resolve dependency for ':app@debug/compileClasspath': Could not resolve com.mikepenz:aboutlibraries:6.0.1.

### ISSUE THREAD

**Issue by francis-95** [singhkshitij/MagicPrint-ECommerce-App-Android#25]
Relation with Issue #23

Hi there,

This issue is stopping me from executing the application in mobile.

**Comment by tameem1993** [comment]
com.mikepenz:aboutlibraries:6.0.1.
to
com.mikepenz:aboutlibraries:6.1.1.
