### ISSUE TITLE
Android resource linking failed

### ISSUE THREAD

**Issue by OkToe1** [singhkshitij/MagicPrint-ECommerce-App-Android#4]
Output:  
C:\Users\HP\Desktop\LCO\Idea2\MagicPrint-master\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values-v28\values-v28.xml:7: error: resource android:attr/dialogCornerRadius not found.
C:\Users\HP\Desktop\LCO\Idea2\MagicPrint-master\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values-v28\values-v28.xml:11: error: resource android:attr/dialogCornerRadius not found.
C:\Users\HP\Desktop\LCO\Idea2\MagicPrint-master\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml:1196: error: resource android:attr/fontVariationSettings not found.
C:\Users\HP\Desktop\LCO\Idea2\MagicPrint-master\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml:1196: error: resource android:attr/ttcIndex not found.
error: failed linking references.

Command: C:\Users\HP\.gradle\caches\transforms-1\files-1.1\aapt2-3.2.1-4818971-windows.jar\70f5f22261ef224f5a15dc47f809a951\aapt2-3.2.1-4818971-windows\aapt2.exe link -I\
        C:\Users\HP\AppData\Local\Android\Sdk\platforms\android-27\android.jar\
        --manifest\
        C:\Users\HP\Desktop\LCO\Idea2\MagicPrint-master\app\build\intermediates\merged_manifests\debug\processDebugManifest\merged\AndroidManifest.xml\
        -o\
        C:\Users\HP\Desktop\LCO\Idea2\MagicPrint-master\app\build\intermediates\processed_res\debug\processDebugResources\out\resources-debug.ap_\
        -R\
        @C:\Users\HP\Desktop\LCO\Idea2\MagicPrint-master\app\build\intermediates\incremental\processDebugResources\resources-list-for-resources-debug.ap_.txt\
        --auto-add-overlay\
        --java\
        C:\Users\HP\Desktop\LCO\Idea2\MagicPrint-master\app\build\generated\not_namespaced_r_class_sources\debug\processDebugResources\r\
        --proguard\
        C:\Users\HP\Desktop\LCO\Idea2\MagicPrint-master\app\build\intermediates\proguard-rules\debug\aapt_rules.txt\
        --custom-package\
        com.beingdev.magicprint\
        -0\
        apk\
        --output-text-symbols\
        C:\Users\HP\Desktop\LCO\Idea2\MagicPrint-master\app\build\intermediates\symbols\debug\R.txt\
        --no-version-vectors
Daemon:  AAPT2 aapt2-3.2.1-4818971-windows Daemon #0

**Comment by shubhamtunwal97** [comment]
In your app level Gradle file change the compile SDK version to 28.

**Comment by singhkshitij** [comment]
> In your app level Gradle file change the compile SDK version to 28.

Cool.. Glad you find solution.. Thanks
