### ISSUE TITLE
Failed to resolve

### ISSUE THREAD

**Issue by edwilkerjorge29** [singhkshitij/MagicPrint-ECommerce-App-Android#5]
com:mikepenz:aboutlibraries:6.0.1

com:mikepenz:materialdrawer:6.0.2

**Comment by singhkshitij** [comment]
You can take latest library versions and update them in gradle file to resolve issues

**Comment by Mayuresh0503** [comment]
Thank You Sir,
  It was pleasure to concern and share errors with you.

**Comment by Ryggs** [comment]
ERROR: Failed to resolve: com.mikepenz:aboutlibraries:6.0.1
